-- AlterTable
ALTER TABLE `paynpik_order_status_history` MODIFY `status` ENUM('CREATED', 'QUEUED', 'PREPARING', 'READY', 'READY_FOR_PICKUP', 'OUT_FOR_SERVICE', 'SERVED', 'CANCELLED', 'DISPUTED', 'RESOLVED', 'FOR_REFUND', 'REFUND_COMPLETE') NOT NULL;

-- AlterTable
ALTER TABLE `paynpik_orders` MODIFY `status` ENUM('CREATED', 'QUEUED', 'PREPARING', 'READY', 'READY_FOR_PICKUP', 'OUT_FOR_SERVICE', 'SERVED', 'CANCELLED', 'DISPUTED', 'RESOLVED', 'FOR_REFUND', 'REFUND_COMPLETE') NOT NULL DEFAULT 'CREATED';

-- AlterTable
ALTER TABLE `paynpik_service_stations` ADD COLUMN `isParcelStation` BOOLEAN NOT NULL DEFAULT false;
