import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
  plugins: [
    react(),
    // Customer PWA service worker — generated by Workbox via the plugin.
    // `autoUpdate` so a newer deploy quietly takes over on next reload;
    // the in-app OfflineBanner still owns the user-facing sync state.
    VitePWA({
      registerType: 'autoUpdate',
      injectRegister: 'auto',
      manifest: {
        name: 'VEZEOR',
        short_name: 'VEZEOR',
        description: 'Order from your table — scan, choose, pay.',
        theme_color: '#0B4245',
        background_color: '#ffffff',
        display: 'standalone',
        orientation: 'portrait',
        start_url: '/',
        scope: '/',
        icons: [
          { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any maskable' },
          { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any maskable' },
        ],
      },
      workbox: {
        // Precache the app shell + static assets at build time.
        globPatterns: ['**/*.{js,css,html,svg,ico,png,webmanifest}'],
        // Fall back to the SPA shell on offline navigation; let /api
        // requests flow through the runtime caching rules instead.
        navigateFallback: '/index.html',
        navigateFallbackDenylist: [/^\/api\//],
        runtimeCaching: [
          // Liveness endpoints — NEVER cache. open-status drives the
          // ordering-disabled banner; if we cached "closed" at 7am the
          // user would still see it at 9am after the outlet opened.
          // Same for kitchen-stations and other realtime status reads.
          {
            urlPattern: ({ url, request }) =>
              request.method === 'GET'
              && (url.pathname.includes('/open-status')
                  || url.pathname.includes('/kitchen-stations/mine')
                  || url.pathname.includes('/customer-alerts')),
            handler: 'NetworkOnly',
          },
          // API GETs — network-first with cache fallback. The in-app
          // cachedGet utility already shadows this for cluster bundle
          // + outlet menu; the SW layer covers the rest of the API
          // surface so a hard reload while offline still boots.
          {
            urlPattern: ({ url, request }) =>
              request.method === 'GET' && url.pathname.includes('/api/'),
            handler: 'NetworkFirst',
            options: {
              cacheName: 'paynpik-api',
              networkTimeoutSeconds: 5,
              expiration: { maxEntries: 100, maxAgeSeconds: 60 * 60 * 24 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          // Item / outlet / brand images. Cache-first — images are
          // immutable for a given URL so we keep them around.
          {
            urlPattern: ({ url, request }) =>
              request.destination === 'image',
            handler: 'CacheFirst',
            options: {
              cacheName: 'paynpik-images',
              expiration: { maxEntries: 200, maxAgeSeconds: 60 * 60 * 24 * 30 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
        // /api writes are intentionally NOT handled by the SW. They flow
        // direct to the network so the in-app outbox owns retry +
        // Idempotency-Key replay (the SW can't safely re-send a write
        // because it'd lose the caller's auth context).
      },
    }),
  ],
  server: { port: 5174 },
});
